license="${mod_license}"
issueTrackerURL="https://github.com/MinecraftModDevelopmentMods/MinecraftMineralogy/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/minecraft-mineralogy"
credits="Cyanobacterium, SkyBlade1978, JRIwanek, FoxNekitsune, Proxy, the MMD Team, NeoForge, FML, and the mod authors"
authors="${mod_authors}"
description='''${mod_description}'''

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mixins]]
config="mineralogy.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="orespawn"
type="required"
versionRange="[4.0.6,5.0.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
